### ISSUE TITLE
Having issues 

### ISSUE THREAD

**Issue by Max543** [backslash/AngstStealer#1345]
im having some issues is there a way i can contact you personally?

**Comment by backslash** [comment]
Githubs Issues is designed for the discussion of current issues in case theirs either a bug or theirs something on your end (which other people should learn from). Please just give me the following details:
1. What your issue is?
2. Are you using the latest version IE are you cloning it or are you using the release build: https://github.com/backslash/AngstStealer/releases/tag/2.0
3. What python version are you on.
4. What errors do you get when you run the executable through command line (Drag and drop it into cmd)
5. Other information that you consider of value.

**Comment by Max543** [comment]
1. When i run the compiled angst i get this error Traceback (most recent call last):
File "<dist\obf\angst.py>", line 3, in <module>
File "<frozen angst>", line 224, in <module>
File "<frozen angst>", line 66, in run
FileExistsError: [WinError 183} Cannot create a file when that file already exists
[14876] Failed to xecute script angst

2. not sure i just press download zip in the main thing that was linked on cracked.to

3. latest version

4. no errors at that step

5. None

**Comment by backslash** [comment]
Head over to your %APPDATA% folder, delete any existing folder titled `Angst`, also consider downgrading to the recommended python version (3.7).  I'll add a slight patch to the current code please clone the latest version after this comment.

**Comment by Max543** [comment]
ok thank you, i dont have an angst folder in the roaming section of appdata is it in a different part

**Comment by backslash** [comment]
-_- this is for educational purposes and I do not condone nor recommend you use this for malicious purposes if you are to incompetent to understand how it works then you shouldn't be using it

**Comment by Max543** [comment]
i wanna test it with my friends.....
